//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.AptitudeAnswers = new HashSet<AptitudeAnswer>();
        }
    
        public int CandidateID { get; set; }
        public string CandidateName { get; set; }
        public string CandidateEmail { get; set; }
        public long CandidateMobileNo { get; set; }
        public string CandidateLocation { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CandidateImg { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string CandidateGender { get; set; }
        public Nullable<System.DateTime> CandidateDateOfBirth { get; set; }
        public Nullable<int> SSC_Marks { get; set; }
        public string SSC_School { get; set; }
        public Nullable<int> HSC_Marks { get; set; }
        public string HSC_College { get; set; }
        public Nullable<int> UG_Marks { get; set; }
        public string UG_College { get; set; }
        public string Skill_1 { get; set; }
        public string Skill_2 { get; set; }
        public string Skill_3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AptitudeAnswer> AptitudeAnswers { get; set; }
    }
}
